### Customer signUp
POST http://localhost:8080/customer/signup
Content-Type: application/json

{
  "email": "ddd@naver.com",
  "name" : "김일번",
  "password": "11223344",
  "phone": "010-1111-2222"
}

### Customer SignIn
POST http://localhost:8080/customer/signin/token
Content-Type: application/json

{
  "email": "ddd@naver.com",
  "password": "11223344"
}