
### Add Category
POST http://localhost:8080/category?name=신발

### Add Product
POST http://localhost:8080/product
Content-Type: application/json
Authorization:

{
  "category": "신발",
  "name": "나이키 에어포스1",
  "description": "신발입니다",
  "price": 120000,
  "stock": 10
}

### Update Product
PUT http://localhost:8080/product?id=14
Content-Type: application/json
Authorization:

{
  "name": "나이키 에어포스1 SE",
  "description": "한정판 신발입니다.",
  "price": 180000,
  "stock": 10
}