
### Add Category
POST http://localhost:8080/category?name=신발

### Add Product
POST http://localhost:8080/product
Content-Type: application/json
Authorization:

{
  "category": "신발",
  "name": "나이키 조던1 범고래",
  "description": "범고래 조던입니다.",
  "price": 210000,
  "stock": 10
}

### Update Product
PUT http://localhost:8080/product?id=5
Content-Type: application/json
Authorization:

{
  "name": "나이키 에어포스1 SE",
  "description": "한정판 신발입니다.",
  "price": 180000,
  "stock": 10
}

### 상품 카테고리 별 최신순 조회
GET http://localhost:8080/categories/2/products/latest?page=1

### Product의 id로 상품 검색
GET http://localhost:8080/product/5