
### Seller signUp
POST http://localhost:8080/seller/signup
Content-Type: application/json

{
  "email": "aaa@naver.com",
  "password": "11223344",
  "phone": "010-1111-2222"
}

### Seller SignIn
POST http://localhost:8080/seller/signin/token
Content-Type: application/json

{
  "email": "aaa@naver.com",
  "password": "11223344"
}
