### 토큰 유효성 테스트
GET http://localhost:8080/admin/token/validation
AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYWFAbmF2ZXIuY29tIiwianRpIjoiMiIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjg4MzU4NzY3LCJleHAiOjE2ODgzNjk1Njd9.W351Py6-xFEEKZaqAR051zJwdoSQyN3WwDu2GbecxWk