### Token Validity Test
GET http://localhost:8080/admin/token/validation
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYWFAbmF2ZXIuY29tIiwianRpIjoiMSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjg4NDc3NjQyLCJleHAiOjE2ODg0ODg0NDJ9.z_CGPMacYlcAdQwZEgkJo6L7JB_fSsdycHYT2gy157g

### Send Auth-Mail
POST http://localhost:8080/admin/auth/mail
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYWFAbmF2ZXIuY29tIiwianRpIjoiMSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjg4NDc3NjQyLCJleHAiOjE2ODg0ODg0NDJ9.z_CGPMacYlcAdQwZEgkJo6L7JB_fSsdycHYT2gy157g